[package]
name = "gpu_flow_fields"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
wgpu = "0.16.0"